Issue/28
wisdomify/storyteller pull request #39
Opened 2021-11-08 13:07 UTC by ArtemisDicoTiar

closes #28

2021-11-08 20:11 UTC, eubinecto requested changes

2021-11-08 20:11 UTC, eubinecto commented on storyteller/preprocess.py
> +    df['eg'] = df['eg'].apply(lambda r: spell_checker.check(r).checked)  # grammar check
`py_hanspell` 설치하지 말아주세요! 라이브러리를 살펴보니까 핵심로직이 정말 별거 없네요. 그냥 request 찌르고 파싱하는게 다네요.  `explore_naver_grammar_checker` 스크립트를 작성했습니다 (82dbb1aee94b06e5d2531f74ed9a28a835a3ad51) - 이거 참고해서 그냥 라이브러리에 의존하지 않는 코드로 변경해주세요!

2021-11-08 20:11 UTC, eubinecto commented on storyteller/preprocess.py
> +    df['eg'] = df['eg'].apply(lambda r: emoticon_normalize(only_text(r), num_repeats=1))
only_text()를 거치는 이유는 뭔가요?

2021-11-09 04:32 UTC, ArtemisDicoTiar commented on storyteller/preprocess.py
> +    df['eg'] = df['eg'].apply(lambda r: emoticon_normalize(only_text(r), num_repeats=1))
💡이런 이모티콘 같은 특수문자 제거입니다

2021-11-09 04:49 UTC, ArtemisDicoTiar commented on storyteller/preprocess.py
> +    df['eg'] = df['eg'].apply(lambda r: spell_checker.check(r).checked)  # grammar check
수정했습니다.

2021-11-09 23:00 UTC, merged